export const electionData = {
  "2024": {
    candidates: [
      {
        id: "slpp",
        name: "Anura Dissanayake",
        party: "National People's Power (NPP)",
        electoralVotes: 98,
        popularVotes: 5850000,
        image: "/placeholder.svg?height=100&width=100",
        color: "#d32f2f",
      },
      {
        id: "sjb",
        name: "Sajith Premadasa",
        party: "Samagi Jana Balawegaya (SJB)",
        electoralVotes: 72,
        popularVotes: 4920000,
        image: "/placeholder.svg?height=100&width=100",
        color: "#1976d2",
      },
      {
        id: "slfp",
        name: "Ranil Wickremesinghe",
        party: "United National Party (UNP)",
        electoralVotes: 35,
        popularVotes: 2750000,
        image: "/placeholder.svg?height=100&width=100",
        color: "#388e3c",
      },
      {
        id: "jvp",
        name: "Namal Rajapaksa",
        party: "Sri Lanka Podujana Peramuna (SLPP)",
        electoralVotes: 20,
        popularVotes: 1980000,
        image: "/placeholder.svg?height=100&width=100",
        color: "#7b1fa2",
      },
    ],
    totalVotes: 15500000,
    districts: [
      { name: "Colombo", code: "CO", electoralVotes: 18, winner: "slpp", margin: 5.2 },
      { name: "Gampaha", code: "GA", electoralVotes: 17, winner: "sjb", margin: 3.1 },
      { name: "Kalutara", code: "KT", electoralVotes: 12, winner: "slpp", margin: 7.5 },
      { name: "Kandy", code: "KY", electoralVotes: 15, winner: "slpp", margin: 4.7 },
      { name: "Matale", code: "MT", electoralVotes: 8, winner: "sjb", margin: 2.8 },
      { name: "Nuwara Eliya", code: "NE", electoralVotes: 10, winner: "slfp", margin: 6.3 },
      { name: "Galle", code: "GL", electoralVotes: 12, winner: "slpp", margin: 8.9 },
      { name: "Matara", code: "MR", electoralVotes: 10, winner: "slpp", margin: 9.2 },
      { name: "Hambantota", code: "HB", electoralVotes: 8, winner: "jvp", margin: 12.5 },
      { name: "Jaffna", code: "JA", electoralVotes: 11, winner: "sjb", margin: 15.3 },
      { name: "Vanni", code: "VA", electoralVotes: 8, winner: "sjb", margin: 11.7 },
      { name: "Batticaloa", code: "BT", electoralVotes: 9, winner: "sjb", margin: 14.2 },
      { name: "Digamadulla", code: "DG", electoralVotes: 10, winner: "sjb", margin: 8.3 },
      { name: "Trincomalee", code: "TC", electoralVotes: 7, winner: "sjb", margin: 5.8 },
      { name: "Kurunegala", code: "KG", electoralVotes: 16, winner: "slpp", margin: 7.1 },
      { name: "Puttalam", code: "PX", electoralVotes: 10, winner: "slfp", margin: 3.5 },
      { name: "Anuradhapura", code: "AD", electoralVotes: 11, winner: "slpp", margin: 6.8 },
      { name: "Polonnaruwa", code: "PR", electoralVotes: 7, winner: "slfp", margin: 4.7 },
      { name: "Badulla", code: "BD", electoralVotes: 12, winner: "sjb", margin: 5.5 },
      { name: "Monaragala", code: "MN", electoralVotes: 8, winner: "slpp", margin: 9.2 },
      { name: "Ratnapura", code: "RT", electoralVotes: 13, winner: "slpp", margin: 8.7 },
      { name: "Kegalle", code: "KE", electoralVotes: 11, winner: "slfp", margin: 2.9 },
    ],
    updates: [
      {
        id: 1,
        time: "9:45 PM",
        district: "Colombo",
        message: "NPP takes lead in Colombo with 42% of votes counted, showing strong urban support.",
        type: "update",
      },
      {
        id: 2,
        time: "9:30 PM",
        district: "Gampaha",
        message: "Gampaha called for SJB with 38.4% of the vote.",
        type: "called",
      },
      {
        id: 3,
        time: "9:15 PM",
        district: "Kandy",
        message: "Early results show NPP leading in key central province districts.",
        type: "update",
      },
      {
        id: 4,
        time: "9:00 PM",
        district: "Jaffna",
        message: "Projection shows SJB with strong lead in northern province.",
        type: "projection",
      },
      {
        id: 5,
        time: "8:45 PM",
        district: "Hambantota",
        message: "Hambantota called for SLPP with 44.1% of the vote.",
        type: "called",
      },
      {
        id: 6,
        time: "8:30 PM",
        district: "Nuwara Eliya",
        message: "UNP showing stronger than expected performance in plantation areas.",
        type: "update",
      },
      {
        id: 7,
        time: "8:15 PM",
        district: "Batticaloa",
        message: "Results from eastern province showing strong turnout for SJB.",
        type: "update",
      },
      {
        id: 8,
        time: "8:00 PM",
        district: "Kurunegala",
        message: "Early results show tight race with NPP slightly ahead.",
        type: "update",
      },
    ],
  },
  "2020": {
    candidates: [
      {
        id: "slpp",
        name: "Gotabaya Rajapaksa",
        party: "Sri Lanka Podujana Peramuna (SLPP)",
        electoralVotes: 128,
        popularVotes: 6924255,
        image: "/placeholder.svg?height=100&width=100",
        color: "#7b1fa2",
      },
      {
        id: "ndf",
        name: "Sajith Premadasa",
        party: "New Democratic Front (NDF)",
        electoralVotes: 85,
        popularVotes: 5564239,
        image: "/placeholder.svg?height=100&width=100",
        color: "#1976d2",
      },
      {
        id: "jvp",
        name: "Anura Kumara Dissanayake",
        party: "National People's Power (NPP)",
        electoralVotes: 7,
        popularVotes: 418553,
        image: "/placeholder.svg?height=100&width=100",
        color: "#d32f2f",
      },
      {
        id: "slfp",
        name: "Mahesh Senanayake",
        party: "National People's Movement (NPM)",
        electoralVotes: 5,
        popularVotes: 49655,
        image: "/placeholder.svg?height=100&width=100",
        color: "#388e3c",
      },
    ],
    totalVotes: 13387609,
    districts: [
      { name: "Colombo", code: "CO", electoralVotes: 18, winner: "ndf", margin: 3.2 },
      { name: "Gampaha", code: "GA", electoralVotes: 17, winner: "slpp", margin: 5.1 },
      { name: "Kalutara", code: "KT", electoralVotes: 12, winner: "slpp", margin: 12.0 },
      { name: "Kandy", code: "KY", electoralVotes: 15, winner: "slpp", margin: 2.7 },
      { name: "Matale", code: "MT", electoralVotes: 8, winner: "slpp", margin: 8.8 },
      { name: "Nuwara Eliya", code: "NE", electoralVotes: 10, winner: "ndf", margin: 11.3 },
      { name: "Galle", code: "GL", electoralVotes: 12, winner: "slpp", margin: 18.9 },
      { name: "Matara", code: "MR", electoralVotes: 10, winner: "slpp", margin: 23.2 },
      { name: "Hambantota", code: "HB", electoralVotes: 8, winner: "slpp", margin: 29.5 },
      { name: "Jaffna", code: "JA", electoralVotes: 11, winner: "ndf", margin: 65.3 },
      { name: "Vanni", code: "VA", electoralVotes: 8, winner: "ndf", margin: 51.7 },
      { name: "Batticaloa", code: "BT", electoralVotes: 9, winner: "ndf", margin: 64.2 },
      { name: "Digamadulla", code: "DG", electoralVotes: 10, winner: "ndf", margin: 28.3 },
      { name: "Trincomalee", code: "TC", electoralVotes: 7, winner: "ndf", margin: 15.8 },
      { name: "Kurunegala", code: "KG", electoralVotes: 16, winner: "slpp", margin: 17.1 },
      { name: "Puttalam", code: "PX", electoralVotes: 10, winner: "slpp", margin: 3.5 },
      { name: "Anuradhapura", code: "AD", electoralVotes: 11, winner: "slpp", margin: 16.8 },
      { name: "Polonnaruwa", code: "PR", electoralVotes: 7, winner: "slpp", margin: 14.7 },
      { name: "Badulla", code: "BD", electoralVotes: 12, winner: "ndf", margin: 5.5 },
      { name: "Monaragala", code: "MN", electoralVotes: 8, winner: "slpp", margin: 19.2 },
      { name: "Ratnapura", code: "RT", electoralVotes: 13, winner: "slpp", margin: 18.7 },
      { name: "Kegalle", code: "KE", electoralVotes: 11, winner: "slpp", margin: 12.9 },
    ],
    updates: [
      {
        id: 1,
        time: "Nov 17, 11:25 AM",
        district: "Colombo",
        message: "NDF wins Colombo district with 51.2% of the vote.",
        type: "called",
      },
      {
        id: 2,
        time: "Nov 17, 10:30 AM",
        district: "Gampaha",
        message: "SLPP takes Gampaha with 52.6% of the vote.",
        type: "called",
      },
      {
        id: 3,
        time: "Nov 17, 9:45 AM",
        district: "Jaffna",
        message: "NDF wins Jaffna with overwhelming 83.1% majority.",
        type: "called",
      },
      {
        id: 4,
        time: "Nov 17, 9:00 AM",
        district: "Hambantota",
        message: "SLPP secures Hambantota with 65.2% of the vote.",
        type: "called",
      },
      {
        id: 5,
        time: "Nov 17, 8:30 AM",
        district: "Kandy",
        message: "SLPP narrowly wins Kandy with 50.8% of the vote.",
        type: "called",
      },
      {
        id: 6,
        time: "Nov 17, 8:00 AM",
        district: "Batticaloa",
        message: "NDF wins Batticaloa with 82.1% of the vote.",
        type: "called",
      },
      {
        id: 7,
        time: "Nov 17, 7:30 AM",
        district: "Kurunegala",
        message: "SLPP secures Kurunegala with 58.6% of the vote.",
        type: "called",
      },
      {
        id: 8,
        time: "Nov 17, 7:00 AM",
        district: "Badulla",
        message: "NDF wins Badulla with 52.8% of the vote.",
        type: "called",
      },
    ],
  },
  "2016": {
    candidates: [
      {
        id: "unf",
        name: "Maithripala Sirisena",
        party: "New Democratic Front (NDF)",
        electoralVotes: 115,
        popularVotes: 6217162,
        image: "/placeholder.svg?height=100&width=100",
        color: "#1976d2",
      },
      {
        id: "upfa",
        name: "Mahinda Rajapaksa",
        party: "United People's Freedom Alliance (UPFA)",
        electoralVotes: 105,
        popularVotes: 5768090,
        image: "/placeholder.svg?height=100&width=100",
        color: "#7b1fa2",
      },
      {
        id: "jvp",
        name: "Anil Dissanayake",
        party: "Janatha Vimukthi Peramuna (JVP)",
        electoralVotes: 3,
        popularVotes: 680486,
        image: "/placeholder.svg?height=100&width=100",
        color: "#d32f2f",
      },
      {
        id: "other",
        name: "Other Candidates",
        party: "Various Parties",
        electoralVotes: 2,
        popularVotes: 234062,
        image: "/placeholder.svg?height=100&width=100",
        color: "#607d8b",
      },
    ],
    totalVotes: 12264377,
    districts: [
      { name: "Colombo", code: "CO", electoralVotes: 18, winner: "unf", margin: 6.2 },
      { name: "Gampaha", code: "GA", electoralVotes: 17, winner: "unf", margin: 4.1 },
      { name: "Kalutara", code: "KT", electoralVotes: 12, winner: "upfa", margin: 2.5 },
      { name: "Kandy", code: "KY", electoralVotes: 15, winner: "unf", margin: 7.7 },
      { name: "Matale", code: "MT", electoralVotes: 8, winner: "unf", margin: 5.8 },
      { name: "Nuwara Eliya", code: "NE", electoralVotes: 10, winner: "unf", margin: 11.3 },
      { name: "Galle", code: "GL", electoralVotes: 12, winner: "upfa", margin: 8.9 },
      { name: "Matara", code: "MR", electoralVotes: 10, winner: "upfa", margin: 9.2 },
      { name: "Hambantota", code: "HB", electoralVotes: 8, winner: "upfa", margin: 12.5 },
      { name: "Jaffna", code: "JA", electoralVotes: 11, winner: "unf", margin: 45.3 },
      { name: "Vanni", code: "VA", electoralVotes: 8, winner: "unf", margin: 31.7 },
      { name: "Batticaloa", code: "BT", electoralVotes: 9, winner: "unf", margin: 44.2 },
      { name: "Digamadulla", code: "DG", electoralVotes: 10, winner: "unf", margin: 18.3 },
      { name: "Trincomalee", code: "TC", electoralVotes: 7, winner: "unf", margin: 15.8 },
      { name: "Kurunegala", code: "KG", electoralVotes: 16, winner: "upfa", margin: 7.1 },
      { name: "Puttalam", code: "PX", electoralVotes: 10, winner: "unf", margin: 3.5 },
      { name: "Anuradhapura", code: "AD", electoralVotes: 11, winner: "upfa", margin: 6.8 },
      { name: "Polonnaruwa", code: "PR", electoralVotes: 7, winner: "unf", margin: 4.7 },
      { name: "Badulla", code: "BD", electoralVotes: 12, winner: "unf", margin: 15.5 },
      { name: "Monaragala", code: "MN", electoralVotes: 8, winner: "upfa", margin: 9.2 },
      { name: "Ratnapura", code: "RT", electoralVotes: 13, winner: "upfa", margin: 8.7 },
      { name: "Kegalle", code: "KE", electoralVotes: 11, winner: "unf", margin: 2.9 },
    ],
    updates: [
      {
        id: 1,
        time: "Jan 9, 11:25 AM",
        district: "Colombo",
        message: "NDF wins Colombo district with 53.1% of the vote.",
        type: "called",
      },
      {
        id: 2,
        time: "Jan 9, 10:30 AM",
        district: "Gampaha",
        message: "NDF takes Gampaha with 52.1% of the vote.",
        type: "called",
      },
      {
        id: 3,
        time: "Jan 9, 9:45 AM",
        district: "Jaffna",
        message: "NDF wins Jaffna with overwhelming 74.4% majority.",
        type: "called",
      },
      {
        id: 4,
        time: "Jan 9, 9:00 AM",
        district: "Hambantota",
        message: "UPFA secures Hambantota with 56.3% of the vote.",
        type: "called",
      },
      {
        id: 5,
        time: "Jan 9, 8:30 AM",
        district: "Kandy",
        message: "NDF wins Kandy with 53.9% of the vote.",
        type: "called",
      },
      {
        id: 6,
        time: "Jan 9, 8:00 AM",
        district: "Batticaloa",
        message: "NDF wins Batticaloa with 72.1% of the vote.",
        type: "called",
      },
      {
        id: 7,
        time: "Jan 9, 7:30 AM",
        district: "Kurunegala",
        message: "UPFA secures Kurunegala with 53.6% of the vote.",
        type: "called",
      },
      {
        id: 8,
        time: "Jan 9, 7:00 AM",
        district: "Badulla",
        message: "NDF wins Badulla with 57.8% of the vote.",
        type: "called",
      },
    ],
  },
}
