'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@asgardeo/auth-react";
import "./globals.css";
import Footer from "@/components/ui/Footer";
import Header from "@/components/ui/Header";

const config = {
  signInRedirectURL: process.env.NEXT_PUBLIC_SIGN_IN_REDIRECT_URL || "https://localhost:3000",
  signOutRedirectURL: process.env.NEXT_PUBLIC_SIGN_OUT_REDIRECT_URL || "https://localhost:3000",
  clientID: process.env.NEXT_PUBLIC_CLIENT_ID || "",
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL || "",
  scope: process.env.NEXT_PUBLIC_SCOPE ? process.env.NEXT_PUBLIC_SCOPE.split(",") : ["openid", "profile"],
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "E-Voting System",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider config={config}>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
