import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/Footer"; // Ensure the path is correct
import { Toaster } from "@/components/ui/toaster";
import ConditionalHeader from "@/components/ui/ConditionalHeader"; // Import conditional header

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Voting System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConditionalHeader /> {/* This will show appropriate header based on route */}
        <main className="min-h-screen">{children}</main>
        <Footer /> {/* Footer remains at the bottom */}
        <Toaster />
      </body>
    </html>
  );
}